version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=https://api.soulvents.com
      - VITE_WS_URL=wss://api.soulvents.com
      - VITE_RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID} # Ensure this is set in your environment or .env file
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Ensure this file exists and is correctly configured
      - /etc/letsencrypt:/etc/letsencrypt # Ensure this directory exists and contains SSL certificates
    networks:
      - soulvents-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  soulvents-network:
    external: true
