services:
  api:
    container_name: soulvents-backend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://postgres:Admin123@soulvents-postgres:5432/postgres
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SMTP_HOST=smtpout.secureserver.net        # GoDaddy SMTP server
      - SMTP_PORT=465                            # Port for TLS
      - SMTP_SECURE=true                         # Enable TLS (true for port 587)
      - SMTP_USER=${SMTP_USER}        # Your full GoDaddy email address
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=SoulVents Support <support@soulvents.com>
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - soulvents-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: soulvents-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - soulvents-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  nginx:
    container_name: soulvents-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/soulvents:/etc/nginx/sites-enabled/soulvents
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount Let's Encrypt certificates
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - soulvents-network
    depends_on:
      - api

networks:
  soulvents-network:
    driver: bridge

volumes:
  postgres-data: